#!/usr/bin/env python
from CSHLDAP import CSHLDAP
from datetime import date, datetime
from csh_webnews import Webnews
import argparse

def checkBirthday(ldap):
    today = date.today()
    for member in allMembersWithBirthdaysOnDate(ldap, today):
        name = member["displayName"]
        if len(name) < 1:
            continue
        displayName = name[0]

def allMembersWithBirthdays(ldap):
    activeMembers = ldap.search(active="1")
    members = []
    for memberTuple in activeMembers:
        if len(memberTuple) < 1:
            continue
        member = memberTuple[1]
        birthday = birthdateFromMember(member)
        if not birthday:
            continue
        members.append(member)
    return members

def allMembersWithBirthdaysOnDate(ldap, date):
    allMembers = allMembersWithBirthdays(ldap)
    birthdayMembers = []
    for member in allMembers:
        birthday = birthdateFromMember(member)
        if date.month != birthday.month or date.day != birthday.day:
            continue
        birthdayMembers.append(member)
    return birthdayMembers

def birthdateFromMember(member):
    if not "birthday" in member:
        return None
    birthday = member["birthday"]
    if len(birthday) < 1:
        return None
    birthdayString = birthday[0]
    memberMonthDay = birthdayString[:8]
    birthdate = datetime.strptime(memberMonthDay, "%Y%m%d")
    return date(year=birthdate.year, month=birthdate.month, day=birthdate.day)

def message(ldap):
    day = date.today()
    birthdays = allMembersWithBirthdaysOnDate(ldap, day)
    numberOfBirthdays = len(birthdays)
    if numberOfBirthdays == 0:
        return None
    plural = "s" if numberOfBirthdays > 1 else ""
    subject = "Today's Birthday" + plural
    string = ""
    for member in birthdays:
        birthdate = birthdateFromMember(member)
        age = date.today().year - birthdate.year
        name = member["displayName"]
        if len(name) < 1:
            continue
        nameString = name[0]
        memberString = nameString + " is " + str(age) + " years old.\n"
        string += memberString
    string += "\nShower on sight!\n\n(This post was automatically generated by the WebNews Birthday Bot.)"
    return subject, string

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Find users with a birthday.')
    parser.add_argument("user", help="Specify a username.")
    parser.add_argument("password", help="Specify the password for the user.")
    parser.add_argument("apikey", help="API key for posting to WebNews")
    parser.add_argument("--test", "-t",
                        action="store_true",
                        help="Posts to csh.test instead of csh.noise")
    args = parser.parse_args()
    ldap = CSHLDAP(args.user, args.password)
    subject, message = message(ldap)
    if not message:
        print("No birthdays today.")
        exit()
    if not args.apikey:
        print("No API key provided.")
        exit()
    newsgroup = "csh.test" if args.test else "csh.noise"
    webnews = Webnews(api_key=args.apikey, api_agent="WebNews Birthday Bot")
    webnews.compose(newsgroup=newsgroup, subject=subject, body=message)
    print(message)
